### ISSUE TITLE
decide on convention for component selectors  

### ISSUE THREAD

**Issue by yutakahoulette** [flimflamjs/ff-core#5]
should we use classes (`class='ff-componentName'`) or data attributes (`data-ff-componentName`) or something else like [aria-labels](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute) (`aria-label='ff-componentName'`) ??

**Comment by jayrbolton** [comment]
We decided on going with data attributes, ie `data-ff-modal`
